language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - sudo apt-get update
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest pytest-cov coverage codecov flake8
  - python setup.py install

script:
  - flake8 --extend-ignore=E701,E501 xone
  - pytest --doctest-module --cov -v xone

after_success:
  - coverage report
  - cat .coverage
  - codecov --token=9debe549-7e1a-429f-b9a4-eed080032d59

