language: python

python:
  - "3.6"
  - "3.7"

install:
  - sudo apt-get update
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install flake8
  - python setup.py install

script:
  - flake8 --extend-ignore=E701,E501 xone
  - pytest xone

after_success:
  - coverage report
  - cat .coverage
  - codecov --token=9debe549-7e1a-429f-b9a4-eed080032d59

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true

#deploy:
#  provider: pypi
#  user: alpha.xone
#  password:
#    secure: ""
#  skip_existing: true
#  on:
#    tags: true
#    distributions: sdist bdist_wheel
#    repo: alpha.xone/xbbg
#    branch: master
#    condition: $TRAVIS_PYTHON_VERSION == 3.6
